### ISSUE TITLE
Clarify licensing: GPLv2+ or GPLv3+?

### ISSUE THREAD

**Issue by vog** [pushover/pushover.github.io#11]
Most source files state "GPLv2 or later", but COPYING contains GPLv3. This is especially confusing for files which don't contain a separate license marker, such as graphics and music.

I assume we switched from "GPLv2 to later" to "GPLv3 or later", but forgot to adjust the source files accordingly. Am I right here? @roever What do you think?

Also, we should consider renaming the file COPYING to LICENSE, which nowadays seems to be the more usual name.

**Comment by roever** [comment]
yep seems lite we added this current license file about 10 years ago and forgot to update the headers. Anyway I don't really care either way...

**Comment by vog** [comment]
Okay, so let's finish the last steps towards GPLv3+.

**Comment by vog** [comment]
Done.
