### ISSUE TITLE
Switch from SDL-1.2 to SDL-2.0

### ISSUE THREAD

**Issue by vog** [pushover/pushover.github.io#20]
SDL-1.2 is quite aged, its latest release SDL-1.2.15 is from 2012-01-19.

So we should move to SDL-2.0.

Any help is welcome!

**Comment by kilobyte** [comment]
The main reason IMHO is fullscreening being broken on pretty much any modern setup:
 * desktops often use multiple monitors — SDL1.2 tramples upon xrandr settings, failing to even restore them upon exit.  Thus, I for example get both screens set to mirrored, at a bogus resolution, landscaped (and today's desktop environments then save those modified settings).  Curiously, during the game itself, the output is not placed on the left landscape monitor even if set to primary, but on right portrait one, making this... not fun.  In my case, the landscape monitor is only 1280x1024, making the game perfectly playable, but those with HiDPI displays are unhappy.
 * laptops, phones, and stand-alone display panels tend to lack the circuitry to emulate CRT monitors and thus are incapable of non-native resolutions at all.  This results in a small unscaled image in the middle of a black screen.

I'm not opening this as a separate issue, as there's not much you can do about it.  Or rather, you could — with a huge amount of work, just to reproduce fixes already done in SDL2.

**Comment by vog** [comment]
For reference, there is a nice migration guide in the SDL wiki:

* https://wiki.libsdl.org/MigrationGuide

**Comment by vog** [comment]
This issue has been moved to: https://gitlab.com/domino-chain/domino-chain.gitlab.io/issues/7
