### ISSUE TITLE
pushover.desktop icon is missing

### ISSUE THREAD

**Issue by alexmyczko** [pushover/pushover.github.io#22]
what about creating a nice icon for the game?

**Comment by vog** [comment]
Note that we already have an icon:

* https://raw.githubusercontent.com/pushover/pushover.github.io/master/src/description/pushover.ico

It is relatively some, showing two of the dominoes. However, I don't mind improving it.

@alexmyczko: Do you have something specific in mind?

@alexmyczko: Note that this is slightly connected to our wish to replace the main blurry ant character with a better, high-resolution figure, such as a BSD daemon or similar. However, we didn't yet find a volunteer, as this is quite a lot of work. There are many individual pictures to draw and/or to generate.

@roever: What do you think?

**Comment by alexmyczko** [comment]
pushover.ico: MS Windows icon resource - 4 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel

https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#definitions

what about providing it as png or svg?

**Comment by alexmyczko** [comment]
ahh there it is, sorry about the noise. 
https://github.com/pushover/pushover.github.io/blob/master/generated/pushover_64x64.png
