### ISSUE TITLE
Enable pushover to run without music

### ISSUE THREAD

**Issue by vog** [pushover/pushover.github.io#3]
@alexmyczko wrote in #2:
> And I'm also running echo -n > data/*.ogg (zsh) to have the software not go crazy if the oggs are missing. Maybe some --nomusic option, or at least a check to keep running even if the music is not there?

**Comment by vog** [comment]
I'm not a fan of a "--nomusic" option as it is too easy to forget it, and too annoying to type it in.

However, we could simply print a warning to `stderr` if some (or all) `*.ogg` files are missing, and just not play it in that case. Other (graphical) assets are already optional, too.

**Comment by alexmyczko** [comment]
oops, data/*.ogg is the small stuff, should be themes/*.ogg. sounds good to me. well i don't plan to ship the 30 mb music, but maybe a downloader tool, for people who want the music

**Comment by vog** [comment]
The current version of Pushover already works without the music. Also, the sounds are not required in any way. Missing sound files produce a warning message, but that one is harmless and the game works just fine:

```
Can't load sound from file: ...
```

@alexmyczko What exactly did you mean with "go crazy"? Did you mean that we should suppress the warning messages, or did you observe any other issue?

**Comment by vog** [comment]
@alexmyczko What exactly did you mean with "go crazy"? Did you mean that we should suppress the warning messages, or did you observe any other issue?

**Comment by alexmyczko** [comment]
I did not test the case, removing all files completely, I just nulled them, thus that worked just fine. Some software try to open data files, and crash if they are not available. A lot of software do not handle no disk space, out of memory, and data files not around...

**Comment by vog** [comment]
So, what do you need from us to get rid of the "`echo -n >...`" workaround?

Is the current pushover version okay as it is, or do we need to reduce and/or remove the warnings?

**Comment by alexmyczko** [comment]
I guess it's fine. Please close this issue...

**Comment by vog** [comment]
Ok, great!
