### ISSUE TITLE
AppStream integration / Gnome Software Store

### ISSUE THREAD

**Issue by alexmyczko** [pushover/pushover.github.io#7]
You might want to think about gnome software store integration with appstream:

https://wiki.debian.org/AppStream

**Comment by vog** [comment]
Sounds good, but what exactly are we, as upstream, supposed to do here?

Do we just put an AppStream XML into our Git repo? Do we need to install it somewhere? Do we need to register pushover at some app registry? Do we need to upload the XML to some place?

**Comment by alexmyczko** [comment]
Hah, if only I would know :)

**Comment by nightflyer73** [comment]
Please have a look at the following doc for more info about AppStream integration:
https://www.freedesktop.org/software/appstream/docs/index.html

Basically you have to make a file called pushover.appdata.xml (the first part of the name must have the same root of the desktop file name) and place it in /usr/share/metainfo/

You can find the AppData file I made for the Fedora package here:
https://pkgs.rpmfusion.org/cgit/nonfree/pushover.git/tree/

It is then your distribution's job to look for AppData files and make data available through Software Center.

**Comment by musuruan** [comment]
Please have a look at the following doc for more info about AppStream integration:
https://www.freedesktop.org/software/appstream/docs/index.html

Basically you have to make a file called pushover.appdata.xml (the first part of the name must have the same root of the desktop file name) and place it in /usr/share/metainfo/

You can find the AppData file I made for the Fedora package here:
https://pkgs.rpmfusion.org/cgit/nonfree/pushover.git/tree/

It is then your distribution's job to look for AppData files and make data available through Software Center.

**Comment by vog** [comment]
@musuruan Thanks for the hints. I just added the AppData file and let it install to the correct place.
